image: registry.gitlab.com/4tu/spheal

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.common: &common
  script:
    - make $PLATFORM
  artifacts:
    paths:
      - vgedit.$EXT

PC:
  <<: *common
  variables:
    PLATFORM: pc
    EXT: bin

PC-sdl1:
  <<: *common
  variables:
    PLATFORM: pc-sdl1
    EXT: bin-sdl1

WiiU:
  <<: *common
  variables:
    PLATFORM: wiiu
    EXT: wuhb

Switch:
  <<: *common
  variables:
    PLATFORM: switch
    EXT: nro

3ds:
  <<: *common
  variables:
    PLATFORM: 3ds
    EXT: 3dsx

Wii:
  <<: *common
  variables:
    PLATFORM: wii
    EXT: dol
